name: deploy-package

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  # test: 
  #   name: testing
  #   runs-on: Ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '16.x'
  #       registry-url: 'https://registry.npmjs.org'
  #   - name: Installing...
  #     run: npm i
  #   - name: Building...
  #     run: npm run build
  #   - name: Testing...
  #     run: npm run test
  #   - name: Coveralls
  #     uses: codecov/codecov-action@v3

  publish:
    if: ${{ github.event.pull_request.merged }}
    name: npm-publish
    runs-on: Ubuntu-20.04
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Installing...
      run: npm i -g lerna && npm install --force
    - name: Building...
      run: lerna run build --ignore @jsonlang/website
    - name: Config GIT
      run: >-
        git config --global user.email "ahmed.medhat.tawfiq@gmail.com" &&
        git config --global user.name "Ahmed Medhat"
    - name: npm config auth
      run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publishing...
      run: lerna publish from-package --no-private --yes


        
